#!/bin/bash
set -e

APP_DIR=/opt/shr-map
GIT_DIR=/opt/shr-map.git

echo "==> Deploying shr-map..."

export GIT_WORK_TREE=$APP_DIR
export GIT_DIR=$GIT_DIR
git checkout -f main
git reset --hard HEAD

cd $APP_DIR
bun install

cp deploy/shr-map.service /etc/systemd/system/shr-map.service
systemctl daemon-reload

systemctl restart shr-map
echo "==> Deploy complete!"
